# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.py.CorePY
canonical: https://mspbs.gov.py/fhir
version: 0.1
name: CorePY-ImplementationGuide

title: Interoperabilidad de Historia Clínica - PARAGUAY
status: draft
publisher: 
  name: MSP PARAGUAY
  url: https://mspbs.gov.py
description: Ministerio de Salud , PARAGUAY - Interoperabilidad de Historia Clínica IHC - 
jurisdiction: urn:iso:std:iso:3166#PY
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2023+
releaseLabel: ci-build

dependencies:
  hl7.fhir.uv.ips: 1.1.0
  ihe.iti.mhd: 4.2.2
  # fhir.who.ddcc: current
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below..             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Inicio: index.html      
  Perfiles Base:
    "Paciente": StructureDefinition-PacientePy.html
    "Profesional": StructureDefinition-PractitionerPy.html
    "Organización": StructureDefinition-OrganizacionPy.html
  Perfiles Información Clínica:
    "Condition": StructureDefinition-ConditionPy.html
    "MedicationStatement": StructureDefinition-MedicationStatementPy.html   
    "AllergyIntolerance": StructureDefinition-AlergiaPy.html
    "Immunization": StructureDefinition-ImmunizationPy.html
  Perfiles Documentos: 
    "Documento Clínico": StructureDefinition-CompositionPy.html
    "BundleDocument": StructureDefinition-BundleDocPy.html
    "Indice Documentos": StructureDefinition-DocumentReferencePy.html  
  Transacciones:
    "BundleTransaction": StructureDefinition-BundleTransaccPy.html
    "List": StructureDefinition-ListPy.html
    "Estructura IPS": IPS-PY.html
    "Detalle": Transacciones-PY.html   
  Resumen: 
    "Versiones": versiones.html
    "Resumen": artifacts.html
    "Descargas": descarga.html



   